version: '3.5'

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_NAME: postgres
      POSTGRES_SCHEMA: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
volumes:
  postgres: